# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 10:02
from __future__ import unicode_literals

from django.db import models, migrations
from gemDatabase.models import *

def populate_instrument_type(apps, schema_editor):

    InstrumentType(code = "FUTURE_CONTRACT", description = "Future").save()
    InstrumentType(code = "FX_FORWARD", description = "FX Forward").save()
    InstrumentType(code = "ETF", description = "Exchange Traded Fund").save()
    InstrumentType(code = "STOCK", description = "Stock").save()
    InstrumentType(code = "FX_SPOT", description = "FX Spot").save()
    InstrumentType(code = "RISK_PREMIA", description = "FX Spot").save()
    InstrumentType(code = "DATA_FEED", description = "FX Spot").save()


class Migration(migrations.Migration):

    dependencies = [
        ('gemDatabase', '0001_initial'),
    ]

    operations = [
    	migrations.RunPython(populate_instrument_type),
    ]
