# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 23:08
from __future__ import unicode_literals

from django.db import models, migrations
from gemDatabase.models import *

def populate_futures(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.

    Future(code = "CL", description = "Crude Oil Futures", bloomberg_code = "CL", minimum_tick_size = 0.001, contract_size = 1000, point_value = 100, settlement_type = SettlementType["PHYSICAL"], exchange = Exchange["CME"], currency = Currency["USD"]).save()
    Future(code = "NG", description = "Natural Gas Futures", bloomberg_code = "NG", minimum_tick_size = 0.001, contract_size = 1000, point_value = 100, settlement_type = SettlementType["PHYSICAL"], exchange = Exchange["CME"], currency = Currency["USD"]).save()
    
    Instrument(code = "CLG17", description = "Crude Oil Futures contract February 2017", instrument_type = InstrumentType["FUTURE"]).save()
    Instrument(code = "CLH17", description = "Crude Oil Futures contract March 2017", instrument_type = InstrumentType["FUTURE"]).save()
    Instrument(code = "CLJ17", description = "Crude Oil Futures contract April 2017", instrument_type = InstrumentType["FUTURE"]).save()

    FutureContract(instrument = Instrument["CLG17"], future = Future["CL"], first_trade_date = "2016-05-01", last_trade_date = "2017-02-15", month = Month["FEB"], year = 2017).save()
    FutureContract(instrument = Instrument["CLH17"], future = Future["CL"], first_trade_date = "2016-06-01", last_trade_date = "2017-03-15", month = Month["MAR"], year = 2017).save()
    FutureContract(instrument = Instrument["CLJ17"], future = Future["CL"], first_trade_date = "2016-07-01", last_trade_date = "2017-04-15", month = Month["APR"], year = 2017).save()

    
class Migration(migrations.Migration):

    dependencies = [
        ('gemDatabase', '0001_initial'),
    ]

    operations = [
    	migrations.RunPython(populate_futures),
    ]
