# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 13:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gemDatabase', '0002_populateInstrumentTypes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200)),
                ('label', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('instrument_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gemDatabase.InstrumentType')),
            ],
        ),
    ]
