# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 23:08
from __future__ import unicode_literals

from django.db import models, migrations
from gemDatabase.models import *

def populate_reports(apps, schema_editor):

    ReportType(code = "ZERO_VALUE", description = "Zero value report").save()
    ReportType(code = "MISSING_DATA", description = "Missing data report").save()
    ReportType(code = "LARGE_PRICE_MOVE", description = "Large price move report").save()
    
    
class Migration(migrations.Migration):

    dependencies = [
        ('gemDatabase', '0002_populateInstrumentTypes'),
    ]

    operations = [
    	migrations.RunPython(populate_reports),
    ]


