# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 23:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemDatabase', '0002_addFutures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapoint',
            name='value',
            field=models.DecimalField(decimal_places=10, max_digits=30, null=True),
        ),
    ]
