# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 13:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gemDatabase', '0003_instrument'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('pip_size', models.DecimalField(decimal_places=8, max_digits=11)),
                ('base_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_currency', to='gemDatabase.Currency')),
                ('quoted_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quoted_currency', to='gemDatabase.Currency')),
            ],
        ),
        migrations.CreateModel(
            name='DataPointSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DataPointType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Future',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('bloomberg_code', models.CharField(max_length=20)),
                ('minimum_tick_size', models.DecimalField(decimal_places=5, max_digits=9)),
                ('contract_size', models.IntegerField()),
                ('point_value', models.DecimalField(decimal_places=2, max_digits=9)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gemDatabase.Currency')),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gemDatabase.Exchange')),
            ],
        ),
        migrations.CreateModel(
            name='MarketDataPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=10, max_digits=30)),
                ('data_point_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gemDatabase.DataPointSource')),
                ('data_point_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gemDatabase.DataPointType')),
            ],
        ),
        migrations.CreateModel(
            name='SettlementType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='label',
        ),
        migrations.RemoveField(
            model_name='instrumenttype',
            name='label',
        ),
        migrations.AlterField(
            model_name='instrument',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='instrumenttype',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AddField(
            model_name='marketdatapoint',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gemDatabase.Instrument'),
        ),
        migrations.AddField(
            model_name='future',
            name='settlement_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gemDatabase.SettlementType'),
        ),
    ]
