# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 14:06
from __future__ import unicode_literals

from django.db import models, migrations
from gemDatabase.models import *

def populate_currencies(apps, schema_editor):
	Currency.objects.bulk_create([
		Currency(description = "European euro", code = "EUR"),
		Currency(description = "Japanese yen", code = "JPY"),
		Currency(description = "Pound sterling", code = "GBP"),
		Currency(description = "Singapore dollar", code = "SGD"),
		Currency(description = "Swiss franc", code = "CHF"),
		Currency(description = "Turkish lira", code = "TRY"),
		Currency(description = "United States dollar", code = "USD")
	
	])

class Migration(migrations.Migration):

    dependencies = [
        ('gemDatabase', '0004_populateMultipleTables'),
    ]

    operations = [
    	migrations.RunPython(populate_currencies),
    ]
