# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemDatabase', '0006_addReports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
