# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 17:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gemDatabase', '0007_auto_20161028_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('future_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gemDatabase.Future')),
                ('instrument_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gemDatabase.Instrument')),
            ],
        ),
    ]
