# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 18:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gemDatabase', '0007_populateCurrencies'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketdatapoint',
            name='date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='marketdatapoint',
            name='instrument',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gemDatabase.Instrument'),
        ),
    ]
