# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 18:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gemDatabase', '0008_auto_20161023_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentFamily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('future', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gemDatabase.Future')),
            ],
            options={
                'db_table': 'instrument_families',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('bloomberg_code', models.CharField(max_length=20)),
                ('company', models.CharField(max_length=200)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gemDatabase.Currency')),
            ],
            options={
                'db_table': 'stocks',
            },
        ),
        migrations.AddField(
            model_name='instrumentfamily',
            name='stock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gemDatabase.Stock'),
        ),
    ]
