# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 17:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gemDatabase', '0008_datafeed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datafeed',
            old_name='future_id',
            new_name='future',
        ),
        migrations.RenameField(
            model_name='datafeed',
            old_name='instrument_id',
            new_name='instrument',
        ),
    ]
