# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 17:31
from __future__ import unicode_literals


from django.db import models, migrations
from gemDatabase.models import *

def populate_currency_spot_instruments(apps, schema_editor):
    
    Instrument(code = "GBPUSD_SPOT", description = "GBP/USD Spot", instrument_type_id = InstrumentType["FX_SPOT"].id).save()
    Instrument(code = "USDJPY_SPOT", description = "USD/JPY Spot", instrument_type_id = InstrumentType["FX_SPOT"].id).save()
    Instrument(code = "EURUSD_SPOT", description = "EUR/USD Spot", instrument_type_id = InstrumentType["FX_SPOT"].id).save()
    
class Migration(migrations.Migration):

    dependencies = [
        ('gemDatabase', '0008_populateMonths'),
    ]

    operations = [
    	migrations.RunPython(populate_currency_spot_instruments),
    ]
