# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 17:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gemDatabase', '0010_auto_20161029_1737'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='datafeed',
            table='data_feeds',
        ),
    ]
