# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 17:31
from __future__ import unicode_literals


from django.db import models, migrations
from gemDatabase.models import *

def populate_data_feeds(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.

    DataFeed(code = "CL1", description = "Crude Oil continuous front month", future_id = Future["CL"].id, instrument_id = Instrument["CL1"].id).save()
    
class Migration(migrations.Migration):

    dependencies = [
        ('gemDatabase', '0011_auto_20161029_1737'),
    ]

    operations = [
    	migrations.RunPython(populate_data_feeds),
    ]
