# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemDatabase', '0012_addDataFeeds'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafeed',
            name='bloomberg_code',
            field=models.CharField(default='CHRIS/CME_CL1', max_length=20),
            preserve_default=False,
        ),
    ]
