# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 00:37
from django.db import models, migrations
from gemDatabase.models import *

def populate_limit_types(apps, schema_editor):
	
	LimitType(code = "ABSOLUTE", description = "Absolute").save()
	LimitType(code = "PROPORTIONAL", description = "Proportional").save()


    
class Migration(migrations.Migration):

    dependencies = [
        ('gemDatabase', '0014_addSector'),
    ]

    operations = [
    	migrations.RunPython(populate_limit_types),
    ]
