# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 17:31
from __future__ import unicode_literals


from django.db import models, migrations
from gemDatabase.models import *

def populate_currency_pairs(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.

    CurrencyPair(code = "GBPUSD", description = "GBP/USD", pip_size = 0.00001, base_currency_id = Currency["GBP"].id, quoted_currency_id = Currency["USD"].id).save()
    CurrencyPair(code = "USDJPY", description = "USD/JPY", pip_size = 0.001, base_currency_id = Currency["USD"].id, quoted_currency_id = Currency["JPY"].id).save()
    CurrencyPair(code = "EURUSD", description = "EUR/USD", pip_size = 0.00001, base_currency_id = Currency["EUR"].id, quoted_currency_id = Currency["USD"].id).save()
    
class Migration(migrations.Migration):

    dependencies = [
        ('gemDatabase', '0014_futurecontract_bloomberg_code'),
    ]

    operations = [
    	migrations.RunPython(populate_currency_pairs),
    ]
