# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 00:40
from django.db import models, migrations
from gemDatabase.models import *

def populate_account(apps, schema_editor):
	
	AccountGroup(code = "MAIN", description = "Main").save()
	
	Account(code = "GEM", description = "Gem", account_group_id = AccountGroup["MAIN"].id, account_capital = 200000000, volatility_target = 0.15 ).save()
	
    
class Migration(migrations.Migration):

    dependencies = [
        ('gemDatabase', '0015_addLimitTypes'),
    ]

    operations = [
    	migrations.RunPython(populate_account),
    ]
