# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 22:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gemDatabase', '0016_currencypair_bloomberg_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencypair',
            name='instrument',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gemDatabase.Instrument'),
            preserve_default=False,
        ),
    ]
