# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-13 23:48
from django.db import models, migrations
from gemDatabase.models import *

def populate_roundings(apps, schema_editor):
	
	Rounding(instrument_type_id = InstrumentType['FX_FORWARD'].id, value = 10000).save()
	Rounding(instrument_type_id = InstrumentType['FUTURE_CONTRACT'].id, value = 1).save()
	Rounding(instrument_type_id = InstrumentType['STOCK'].id, value = 1).save()	
	
    
class Migration(migrations.Migration):

    dependencies = [
        ('gemDatabase', '0016_addAccount'),
    ]

    operations = [
    	migrations.RunPython(populate_roundings),
    ]
