# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 21:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gemDatabase', '0018_addCurrencySpotInstrument'),
    ]

    operations = [
        migrations.CreateModel(
            name='FutureMonth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('future', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gemDatabase.Future')),
                ('month', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gemDatabase.Month')),
            ],
            options={
                'db_table': 'future_months',
            },
        ),
    ]
