# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 17:31
from __future__ import unicode_literals


from django.db import models, migrations
from gemDatabase.models import *

def populate_data_feeds(apps, schema_editor):
    Instrument(code = "CL1", description = "Crude oil continuous front month instrument", instrument_type = InstrumentType["DATA_FEED"]).save()
    DataFeed(code = "CL1", description = "Crude Oil continuous front month", future_id = Future["CL"].id, instrument_id = Instrument["CL1"].id, bloomberg_code = 'CHRIS/CME_CL1').save()

    Instrument(code = "TY1", description = "TY continuous front month instrument", instrument_type = InstrumentType["DATA_FEED"]).save()
    DataFeed(code = "TY1", description = "TY continuous front month", future_id = Future["TY"].id, instrument_id = Instrument["TY1"].id, bloomberg_code = 'CHRIS/CME_TY1').save()

    Instrument(code = "NG1", description = "NG continuous front month instrument", instrument_type = InstrumentType["DATA_FEED"]).save()
    DataFeed(code = "NG1", description = "NG continuous front month", future_id = Future["NG"].id, instrument_id = Instrument["NG1"].id, bloomberg_code = 'CHRIS/CME_NG1').save()

    DataFeed(code = "GBPUSD_SPOT", description = "GBPUSD_SPOT", currency_pair_id = CurrencyPair["GBPUSD"].id, instrument_id = Instrument["GBPUSD_SPOT"].id, bloomberg_code = CurrencyPair["GBPUSD"].bloomberg_code).save()
    

class Migration(migrations.Migration):

    dependencies = [
        ('gemDatabase', '0019_populateInstruments'),
    ]

    operations = [
    	migrations.RunPython(populate_data_feeds),
    ]
