# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemDatabase', '0020_addFutureMonths'),
    ]

    operations = [
        migrations.AddField(
            model_name='futurecontract',
            name='code',
            field=models.CharField(default='CLH17', max_length=20),
            preserve_default=False,
        ),
    ]
