# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 21:27
from django.db import models, migrations
from gemDatabase.models import *

def populate_future_months(apps, schema_editor):
    
    FutureMonth(future_id = Future["CL"].id, month_id = Month["JAN"].id).save()
    FutureMonth(future_id = Future["CL"].id, month_id = Month["FEB"].id).save()
    FutureMonth(future_id = Future["CL"].id, month_id = Month["MAR"].id).save()
    FutureMonth(future_id = Future["CL"].id, month_id = Month["APR"].id).save()
    FutureMonth(future_id = Future["CL"].id, month_id = Month["MAY"].id).save()
    FutureMonth(future_id = Future["CL"].id, month_id = Month["JUN"].id).save()
    FutureMonth(future_id = Future["CL"].id, month_id = Month["JUL"].id).save()
    FutureMonth(future_id = Future["CL"].id, month_id = Month["AUG"].id).save()
    FutureMonth(future_id = Future["CL"].id, month_id = Month["SEP"].id).save()
    FutureMonth(future_id = Future["CL"].id, month_id = Month["OCT"].id).save()
    FutureMonth(future_id = Future["CL"].id, month_id = Month["NOV"].id).save()
    FutureMonth(future_id = Future["CL"].id, month_id = Month["DEC"].id).save()
    
class Migration(migrations.Migration):

    dependencies = [
        ('gemDatabase', '0020_addDataFeeds'),
    ]

    operations = [
    	migrations.RunPython(populate_future_months),
    ]
