# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-05 14:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gemDatabase', '0023_auto_20161105_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('enabled', models.BooleanField(default=True)),
                ('strategy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gemDatabase.Strategy')),
            ],
            options={
                'db_table': 'trading_models',
            },
        ),
    ]
