# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-05 14:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gemDatabase', '0024_tradingmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingModelFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_feed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gemDatabase.DataFeed')),
                ('trading_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gemDatabase.TradingModel')),
            ],
            options={
                'db_table': 'trading_model_feeds',
            },
        ),
    ]
