# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemDatabase', '0024_addTargetInstruments'),
    ]

    operations = [
        migrations.AddField(
            model_name='fxforward',
            name='code',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fxforward',
            name='description',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
