# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 00:07
from django.db import models, migrations
from gemDatabase.models import *

def populate_sectors(apps, schema_editor):
	
	Sector(code = "FX", description = "FX").save()
	Sector(code = "EQUITIES", description = "Equities").save()
	Sector(code = "INDEX", description = "Index").save()
	Sector(code = "ENERGY", description = "Energy").save()
	Sector(code = "METAL", description = "Metal").save()
	Sector(code = "BOND", description = "Bond").save()
	Sector(code = "FARM", description = "Farm").save()
	Sector(code = "STIR", description = "Stir").save()



    
class Migration(migrations.Migration):

    dependencies = [
        ('gemDatabase', '0030_auto_20161109_0006'),
    ]

    operations = [
    	migrations.RunPython(populate_sectors),
    ]
