# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 00:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gemDatabase', '0034_addAccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioGearing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=10, max_digits=30, null=True)),
                ('account_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gemDatabase.AccountGroup')),
            ],
            options={
                'db_table': 'portfolio_gearings',
            },
        ),
        migrations.CreateModel(
            name='StrategyGearing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=10, max_digits=30, null=True)),
                ('account_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gemDatabase.AccountGroup')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gemDatabase.Strategy')),
            ],
            options={
                'db_table': 'strategy_gearings',
            },
        ),
        migrations.CreateModel(
            name='StrategyTypeGearing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=10, max_digits=30, null=True)),
                ('account_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gemDatabase.AccountGroup')),
                ('strategy_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gemDatabase.StrategyType')),
            ],
            options={
                'db_table': 'strategy_type_gearings',
            },
        ),
        migrations.CreateModel(
            name='StrategyTypeWeight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=10, max_digits=30, null=True)),
                ('account_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gemDatabase.AccountGroup')),
                ('strategy_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gemDatabase.StrategyType')),
            ],
            options={
                'db_table': 'strategy_type_weights',
            },
        ),
        migrations.CreateModel(
            name='StrategyWeight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=10, max_digits=30, null=True)),
                ('account_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gemDatabase.AccountGroup')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gemDatabase.Strategy')),
            ],
            options={
                'db_table': 'strategy_weights',
            },
        ),
        migrations.CreateModel(
            name='TradingModelWeight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=10, max_digits=30, null=True)),
                ('account_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gemDatabase.AccountGroup')),
                ('trading_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gemDatabase.TradingModel')),
            ],
            options={
                'db_table': 'trading_model_weights',
            },
        ),
    ]
