# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 01:58
from django.db import models, migrations
from gemDatabase.models import *

def populate_gearings(apps, schema_editor):
	
	StrategyGearing(account_group_id = AccountGroup["MAIN"].id, strategy_id = Strategy["BOND_MOM"].id, value = 22.0).save()

	StrategyWeight(account_group_id = AccountGroup["MAIN"].id, strategy_id = Strategy["BOND_MOM"].id, value = 3.0 ).save()
	TradingModelWeight(account_group_id = AccountGroup["MAIN"].id, trading_model_id = TradingModel["BOND_MOM_TY"].id, value = 6.0 ).save()
	
	
    
class Migration(migrations.Migration):

    dependencies = [
        ('gemDatabase', '0036_addGearings'),
    ]

    operations = [
    	migrations.RunPython(populate_gearings),
    ]
