# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-12 14:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gemDatabase', '0037_addMoreGearings'),
    ]

    operations = [
        migrations.CreateModel(
            name='FxForward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_date', models.DateField()),
                ('currency_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gemDatabase.CurrencyPair')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gemDatabase.Instrument')),
                ('notional_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gemDatabase.Currency')),
            ],
            options={
                'db_table': 'fx_forwards',
            },
        ),
    ]
