# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-12 18:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gemDatabase', '0038_fxforward'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafeed',
            name='currency_pair',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gemDatabase.CurrencyPair'),
        ),
        migrations.AlterField(
            model_name='datafeed',
            name='future',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gemDatabase.Future'),
        ),
    ]
