# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-13 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemDatabase', '0039_auto_20161112_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetlimit',
            name='side',
            field=models.CharField(default='LONG', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modellimit',
            name='side',
            field=models.CharField(default='LONG', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sectorlimit',
            name='side',
            field=models.CharField(default='LONG', max_length=20),
            preserve_default=False,
        ),
    ]
