# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 10:02
from __future__ import unicode_literals

from django.db import models, migrations
from gemDatabase.models import *

def populate_instrument_type(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    InstrumentType(code = "FUTURE", description = "Future").save()
    InstrumentType(code = "FX_FORWARD", description = "FX Forward").save()
    InstrumentType(code = "ETF", description = "Exchange Traded Fund").save()
    InstrumentType(code = "STOCK", description = "Stock").save()


class Migration(migrations.Migration):

    dependencies = [
        ('gemDatabase', '0001_initial'),
    ]

    operations = [
    	migrations.RunPython(populate_instrument_type),
    ]
