# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 18:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gemDatabase', '0009_auto_20161023_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='FutureContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_trade_date', models.DateField()),
                ('last_trade_date', models.DateField()),
                ('year', models.IntegerField()),
                ('future', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gemDatabase.Future')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gemDatabase.Instrument')),
            ],
            options={
                'db_table': 'future_contracts',
            },
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('month_code', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'months',
            },
        ),
        migrations.AddField(
            model_name='stock',
            name='instrument',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gemDatabase.Instrument'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='futurecontract',
            name='month',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gemDatabase.Month'),
        ),
    ]
