# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 18:56
from __future__ import unicode_literals

from django.db import models, migrations
from gemDatabase.models import *

def populate_months(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.

    Month(code = "JAN", description = "January", month_code = "F").save()
    Month(code = "FEB", description = "February", month_code = "G").save()
    Month(code = "MAR", description = "March", month_code = "H").save()
    Month(code = "APR", description = "April", month_code = "J").save()
    Month(code = "MAY", description = "May", month_code = "K").save()
    Month(code = "JUN", description = "June", month_code = "M").save()
    Month(code = "JUL", description = "July", month_code = "N").save()
    Month(code = "AUG", description = "August", month_code = "Q").save()
    Month(code = "SEP", description = "September", month_code = "U").save()
    Month(code = "OCT", description = "October", month_code = "V").save()
    Month(code = "NOV", description = "November", month_code = "X").save()
    Month(code = "DEC", description = "December", month_code = "Z").save()

class Migration(migrations.Migration):

    dependencies = [
        ('gemDatabase', '0011_populateInstruments'),
    ]

    operations = [
    	migrations.RunPython(populate_months),
    ]
