# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 11:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gemDatabase', '0012_populateMonths'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MarketDataPoint',
            new_name='DataPoint',
        ),
        migrations.AlterModelTable(
            name='datapoint',
            table='data_points',
        ),
    ]
